export const NAV_ITEMS = [
  { id: "dashboard",     label: "Dashboard",     icon: "dashboard"         },
  { id: "patients",      label: "Patients",       icon: "person"            },
  { id: "doctors",       label: "Doctors",        icon: "medical_services"  },
  { id: "appointments",  label: "Appointments",   icon: "event"             },
  { id: "prescriptions", label: "Prescriptions",  icon: "description"       },
  { id: "billing",       label: "Billing",        icon: "payments"          },
  { id: "reports",       label: "Reports",        icon: "bar_chart"         },
];

export const patientNav = [
  { id: "dashboard",     label: "Dashboard",     icon: "dashboard"         },
  { id: "doctors",       label: "Doctors",        icon: "medical_services"  },
  { id: "appointments",  label: "Appointments",   icon: "event"             },
  { id: "prescriptions", label: "Prescriptions",  icon: "description"       },
  { id: "reports",       label: "Reports",        icon: "bar_chart"         },
  { id: "chatBot",       label: "Ai Assistant",    icon: "assistant"         },

]

export const DOCTORS = [
  {
    id: 1,
    name: "Dr. Sarah Jenkins",
    specialty: "Senior Cardiologist",
    experience: "12 years experience",
    rating: "4.9",
    fee: "$120.00",
    availability: "Today",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuAkF1vvabBF8cMAbA2CavXH0Ubtt-UlbiymNYiqmM3CDIdTsiixdQ-gHkqqVLBB8x4R7FlLqJXtH6OBro2KZU7dV7fSaGmbWQ69JHxQ4zzmfXcaCzJ3j-42oLokBx-jeH5_wuVfdzv8vPZfb_TXoSU0xZcu-VGf7zqwMBPnvW_uFoWAx7cFFEumbPjvq8dhTY2Wczhruxwwc3ozI3UzWfkTuZZ7-Csb7fSsizjnwGsci45-coYw6hCrFLYrpYnBXEgPFVN9cA0WljME",
    slots: {
      0: ["09:30 AM", "11:00 AM", "02:30 PM"],
      1: ["10:00 AM", "01:00 PM"],
      3: ["09:00 AM", "11:30 AM", "03:00 PM"],
      5: ["10:30 AM", "12:00 PM"],
    },
  },
  {
    id: 2,
    name: "Dr. Marcus Thorne",
    specialty: "Neurologist",
    experience: "15 years experience",
    rating: "5.0",
    fee: "$150.00",
    availability: "Tomorrow",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDJ3OlQDa0sqYB7N2YSulbzen8xCF1uKPNd26jQvaF76cjcIaeP7dRJuu6pTOLw-5NT9BP05c4IClTh8FW-rvTXNMnvhie5NuLagGHYGpj3DUJxlwZDAzKNtazm8YAdSsV1_GC8n6fzW4A-Wna3ndhiVLqmJlTWtgutnZXmnDCdylq3_Js-BBSqe3plnx9tRK0RMUHF1u0O_Wrk5AWP41FqM9u73zvoGxuRKCRTDU_qNL-kYr-aXGk9dv6WB6oFcLX8hhGWeJnORbfs",
    slots: {
      1: ["10:00 AM", "01:00 PM", "04:30 PM"],
      2: ["09:30 AM", "11:00 AM"],
      4: ["02:00 PM", "04:00 PM"],
    },
  },
  {
    id: 3,
    name: "Dr. Elena Rossi",
    specialty: "Pediatrician",
    experience: "8 years experience",
    rating: "4.8",
    fee: "$95.00",
    availability: "Today",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCbDbQmSPTA3uvgWOlObGnlI3SvanEeO3s7KTB5q_4wK8WAgb3mKuV8rBBUpacp0KZ2UwcTHnDzZloJXmxOXylnyihfHAlV2Ku7CXMlRNk0fZe3pESnP2lLS6h7BjX0vIc_gnWK9zdusA5ongCRH93DxAkBGNpwZXgg6H3qeWR3zOzMBTsLPc5SrJAAI-ru0htoHbWAP3DLIOTIbp-9fxZX8f4HRBh-_7-EFQynA2S8KcEgcwx7lUTMu79IKawwPZmmSK-mp4SdQzeD",
    slots: {
      0: ["08:00 AM", "10:30 AM", "03:00 PM"],
      2: ["09:00 AM", "11:30 AM"],
      3: ["08:30 AM", "01:00 PM", "04:00 PM"],
    },
  },
  {
    id: 4,
    name: "Dr. Julian Vane",
    specialty: "Dermatologist",
    experience: "10 years experience",
    rating: "4.9",
    fee: "$110.00",
    availability: "Today",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDm3FUPtz2LWN3RnyWtXQxXPL_tky60_WQ2gfN7O5jHb8n2yLHH-30_4de-aQLedWjo36z12SKNQp9FR60WBqMvdvZW-QkrV7nnhmmuw8khdToqTiL9gQ7E0WQuKI6vLf2obysyYldobR9FSXE6RYUgLbqpThunBtnytJq8TYSlOSfBUvE4g7N8fYyTezCMfQ-6XLoQOaRnSEZPWc4NgitPFWG3HOUhkETwuDjYtm0rSsw1QaYbVWJL9IoXX0PYqmwzgsVESN-ontCW",
    slots: {
      0: ["11:30 AM", "12:30 PM", "05:00 PM"],
      1: ["10:00 AM", "02:00 PM"],
      4: ["09:00 AM", "11:00 AM", "03:30 PM"],
    },
  },
];


export const DEPARTMENTS = [
  "All Departments", "Cardiology", "Neurology",
  "Pediatrics", "Dermatology", "Orthopedics", "Oncology",
];

export const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
export const MONTHS = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

export const UPCOMING = [
  {
    id: 1,
    name: "Dr. Julian Vance",
    specialty: "Senior Cardiologist",
    location: "North Wing, Floor 4",
    date: "Oct 24, 2023",
    time: "10:30 AM",
    fee: "$120.00",
    status: "Confirmed",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDfybx9VSdMiHwwFiYx8mqzGGSbOawedVKQLXxUILq0bT0yEJCwctLzUAmiow8T2FB6AuNN1FtrwV_E4PLuJbgrCQ07k3H5fGxwQkFP3wh_k0k-TXD2AZ66ivmBCYs3Wj6Dxj77SUmGM51feTvGWIDuZcK5IyIiCZEuTcH6vEGE1j5YuWyDB8QfNzFRdZ9Gv82GDm4F1w6TejAm7jknI5lAP6HMVt0kIm3-N2MJ6m22tIXAfpYa69uAZlN3IcS6Ucfus4l0x3ygu_kX",
  },
  {
    id: 2,
    name: "Dr. Elena Rodriguez",
    specialty: "Dermatology",
    location: "Wellness Center, Suite 12",
    date: "Oct 28, 2023",
    time: "02:15 PM",
    fee: "$85.00",
    status: "Confirmed",
    img: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtRH3r7IvcynNFZmPesL8UN7hDl78UoPdGK8yXG3soTjfXXDBsFoU9qx5_81R96qhjte68rdnfNEEa40XLe6OwEbFMTjfov1SfHfT7e1kan_fVZwRYscv4KzwngSNC9SbY9spX_u8sCMPOIEPUISJNNgRiyR1RsXUgQlFb4wh_Wjbwj0irkWdPHVi4THYrlkLrq2mfffq798DxVaZxqeSfO5k5-kaZ7-WhQ3Zq39u7ItyLD7LNhwbImM8rwgDcjkjCdsraXKYkpeLu",
  },
];


export const ALL_PRESCRIPTIONS = [
  { id: 1,  doctor: "Dr. Sarah Jenkins",  date: "October 12, 2023",   diagnosis: "Acute Bronchitis",         status: "Active",    specialty: "Pulmonology"   },
  { id: 2,  doctor: "Dr. Marcus Thorne",  date: "August 24, 2023",    diagnosis: "Seasonal Allergies",       status: "Completed", specialty: "Immunology"    },
  { id: 3,  doctor: "Dr. Emily Zhang",    date: "July 15, 2023",      diagnosis: "Type 2 Diabetes Mgmt",    status: "Active",    specialty: "Endocrinology" },
  { id: 4,  doctor: "Dr. Robert Chen",    date: "May 02, 2023",       diagnosis: "Post-Op Recovery",         status: "Completed", specialty: "Surgery"       },
  { id: 5,  doctor: "Dr. Maria Lopez",    date: "April 19, 2023",     diagnosis: "Hypertension",             status: "Active",    specialty: "Cardiology"    },
  { id: 6,  doctor: "Dr. James Okafor",   date: "March 08, 2023",     diagnosis: "Migraine Management",      status: "Completed", specialty: "Neurology"     },
  { id: 7,  doctor: "Dr. Priya Nair",     date: "February 22, 2023",  diagnosis: "Iron Deficiency Anemia",   status: "Active",    specialty: "Hematology"    },
  { id: 8,  doctor: "Dr. Lucas Ferreira", date: "January 30, 2023",   diagnosis: "Eczema Treatment",         status: "Completed", specialty: "Dermatology"   },
];


export const MEDICINES = [
  {
    id: 1,
    name: "Atorvastatin Calcium",
    brand: "Brand Name: Lipitor",
    dosage: "20 mg",
    frequency: "Once daily (Evening)",
    freqIcon: "nights_stay",
    duration: "90 Days",
    route: "Oral",
    iconBg: "#eff6ff",
    iconColor: "#004ac6",
    icon: "pill",
  },
  {
    id: 2,
    name: "Lisinopril",
    brand: "Brand Name: Zestril",
    dosage: "10 mg",
    frequency: "Once daily (Morning)",
    freqIcon: "light_mode",
    duration: "30 Days",
    route: "Oral",
    iconBg: "#eff6ff",
    iconColor: "#004ac6",
    icon: "pill",
  },
  {
    id: 3,
    name: "Aspirin Low Dose",
    brand: "ECASA",
    dosage: "81 mg",
    frequency: "Daily",
    freqIcon: "history",
    duration: "Continuous",
    route: "Oral",
    iconBg: "#fff7ed",
    iconColor: "#ea580c",
    icon: "medication",
  },
];


export const ALL_REPORTS = [
  {
    id: 1,
    name: "Blood Panel - Q3 Results",
    size: "1.2 MB • PDF",
    date: "Oct 12, 2023",
    dateObj: new Date(2023, 9, 12),
    source: "Dr. Sarah Jenkins",
    sourceType: "doctor",
    sourceImg: "https://lh3.googleusercontent.com/aida-public/AB6AXuAKqOwgBbNd8eIYQ16_CK3Sz1ymv22HtVzysWHmB3ZMJHIcBMmJvNH1P5JZHy8B07Gz_4XZmE4RGxBBV1EvsSbaMSYhM4OoPHhzBsPjtHOk3DE0zjgqGpSc0TxoNvunePwYayb-KeCC5QPoW8aWqaNR71EE2Vo1ay4wp3knkVljzY64R6oY7GHahmk94-ijGKcL1oTWKtWEEQWF3eUqCyp7L2ChXmICcv_N0SZ3IQwRKbXLhQsrfAW0Zaqg4oS7vxEQfHAxzbUtMxm-",
    status: "Verified",
    starred: true,
    fileType: "pdf",
    category: "Lab Results",
  },
  {
    id: 2,
    name: "Chest X-Ray - Post Op",
    size: "4.8 MB • DICOM",
    date: "Oct 05, 2023",
    dateObj: new Date(2023, 9, 5),
    source: "City General Imaging",
    sourceType: "lab",
    sourceImg: null,
    status: "In Review",
    starred: false,
    fileType: "image",
    category: "Imaging",
  },
  {
    id: 3,
    name: "MRI Scan - Lumbar Spine",
    size: "12.4 MB • PDF",
    date: "Sep 28, 2023",
    dateObj: new Date(2023, 8, 28),
    source: "Dr. Robert Chen",
    sourceType: "doctor",
    sourceImg: "https://lh3.googleusercontent.com/aida-public/AB6AXuCOJOIiKgf7NOQ4FuclW6PDn3oQHVfOrzYuuJTQ8xxlmlzwxvZmvjIlND3QamUuc5zoRvKHBeB9ScxcPQGzgyRD4dzYxwE629_tTlqHvmXQ_NGirQkvHLcJPH1FXqnf2evTh_XVODg2SJgSc9hZH3m3tuOHsgTXfSzwG1SGmgdzyXK1q9w6fp0sapNV6M5zFqzsFG2v-nH9QxbUvIDFL6joxJO6hp9QjU48vNR2cdtTjGg0JBHt7-DQBhawlIrPImSpYAeE3Klvpcag",
    status: "Verified",
    starred: true,
    fileType: "pdf",
    category: "Imaging",
  },
  {
    id: 4,
    name: "Annual Wellness Summary",
    size: "0.8 MB • PDF",
    date: "Aug 15, 2023",
    dateObj: new Date(2023, 7, 15),
    source: "Dr. Sarah Jenkins",
    sourceType: "doctor",
    sourceImg: "https://lh3.googleusercontent.com/aida-public/AB6AXuAIN_OpFj7Z8mv0xPoTee9M68h1LhCXmyZb5kzi7K_my9--r3dMASafnM0MPETnGFkoHzqViA0Tc6BkwZBoFEldox5iO4WIeO-DMlLjNj9LTYD2f9ee686rrKCXVcBh0egwagTQV9758XWFo-TVNy_urfr4fXe5zBF_HPrKSveiHtJIAxp0zvwDQq1tBzdJ7uOcTaIQ51HMEqEEAeBGWIuXL-O4ckXOpl_86UF4yx7K_tLRWpe9A-z7ulxg9Y3zHHvrfaXrBsS8ZR2F",
    status: "Verified",
    starred: false,
    fileType: "pdf",
    category: "Summary",
  },
  {
    id: 5,
    name: "ECG Report - Cardiology",
    size: "0.4 MB • PDF",
    date: "Jul 22, 2023",
    dateObj: new Date(2023, 6, 22),
    source: "Dr. Julian Vance",
    sourceType: "doctor",
    sourceImg: null,
    status: "Verified",
    starred: false,
    fileType: "pdf",
    category: "Lab Results",
  },
  {
    id: 6,
    name: "Ultrasound - Abdomen",
    size: "6.1 MB • DICOM",
    date: "Jun 10, 2023",
    dateObj: new Date(2023, 5, 10),
    source: "Metro Diagnostics",
    sourceType: "lab",
    sourceImg: null,
    status: "In Review",
    starred: false,
    fileType: "image",
    category: "Imaging",
  },
];